/**
 * AUTO-GENERATED by scripts/resolve-modules.mjs — do not edit by hand.
 * Mode: STUB (chatbot disabled / absent)
 * Generated: 2026-08-18T18:21:08.858Z
 */

export {
  ChatbotHost,
  recordSupportNetworkError
} from './stub';
