/**
 * AUTO-GENERATED by scripts/resolve-modules.mjs — do not edit by hand.
 * Mode: MODULE (chatbot enabled)
 * Generated: 2026-08-25T16:17:10.751Z
 */

export {
  ChatbotHost,
  recordSupportNetworkError
} from '../../modules/chatbot';
