/**
 * AUTO-GENERATED by scripts/resolve-modules.mjs — do not edit by hand.
 * Mode: STUB (chatbot disabled / absent)
 * Generated: 2026-08-24T13:28:51.897Z
 */

export {
  ChatbotHost,
  recordSupportNetworkError
} from './stub';
