import { defineConfig } from 'vitest/config';
import react from '@vitejs/plugin-react';
import { fileURLToPath, URL } from 'node:url';

export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url)),
    },
  },
  test: {
    environment: 'jsdom',
    setupFiles: ['./src/test/setup.ts'],
    globals: true,
    include: ['src/**/*.test.{ts,tsx}'],
    exclude: ['e2e/**', 'node_modules/**'],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json-summary', 'html'],
      include: [
        'src/utils/gs1Parser.ts',
        'src/utils/cryptoStore.ts',
        'src/lib/gs1Barcode.ts',
        'src/lib/terminalPasskey.ts',
        'src/hooks/useBarcodeScanner.ts',
        'src/hooks/useHardwareScanner.ts',
        'src/lib/hardwareCapabilities.ts',
        'src/lib/barcodeCameraDecode.ts',
        'src/features/inbound/BarcodeScannerInput.tsx',
        'src/components/hardware/HardwareManualFallback.tsx',
        'src/components/ui/WebRtcCamera.tsx',
        'src/hooks/useDensity.ts',
        'src/hooks/useScannerIdle.ts',
        'src/hooks/useDesktopIdle.ts',
        'src/components/security/IdleWarningModal.tsx',
        'src/components/security/DesktopLockOverlay.tsx',
        'src/components/security/DesktopIdleGate.tsx',
        'src/stores/offlineStore.ts',
        'src/stores/preferencesStore.ts',
        'src/stores/gridColumnStore.ts',
        'src/stores/cryptoMemoryKeyStore.ts',
        'src/stores/scannerLockStore.ts',
        'src/offline/mutationQueue.ts',
        'src/offline/encryptedIdb.ts',
        'src/offline/pinVault.ts',
        'src/offline/scanEvent.ts',
        'src/features/fulfillment/QuarantineReview.tsx',
        'src/features/fulfillment/ScannerView.tsx',
        'src/features/settings/WarehouseVisualizer.tsx',
        'src/features/ingestion/ImportWizard.tsx',
        'src/components/ui/primitives/VirtualizedTable.tsx',
        'src/components/ui/DensityToggle.tsx',
        'src/components/ui/ColumnVisibilityMenu.tsx',
        'src/components/ui/Table.tsx',
        'src/hooks/useClientSort.ts',
        'src/api/inventory.ts',
        'src/hooks/useReverseTransactionMutation.ts',
        'src/features/inventory/LedgerHistoryTable.tsx',
        'src/components/ui/AlertDialog.tsx',
        'src/features/offline/SyncConflictsPanel.tsx',
        'src/features/offline/conflictSummary.ts',
        'src/features/offline/SyncConflictAlertBanner.tsx',
        'src/lib/pageKnowledge/RouteKnowledgeRegistry.ts',
        'src/modules/chatbot/supportChatApi.ts',
        'src/modules/chatbot/SupportAssistantWidget.tsx',
        'src/modules/chatbot/trainingSandboxStore.ts',
        'src/modules/training/trainingSandboxStore.ts',
        'src/modules/chatbot/supportSpotlight.ts',
        'src/components/ui/PageHelpOverlay.tsx',
        'src/api/portal.ts',
        'src/api/mesh.ts',
        'src/api/users.ts',
        'src/api/roles.ts',
        'src/api/settings.ts',
        'src/api/integrations.ts',
        'src/utils/accountAutoMatcher.ts',
        'src/features/settings/integrationProviders.ts',
        'src/features/settings/IntegrationWizardModal.tsx',
        'src/features/settings/IntegrationConnectionCards.tsx',
        'src/pages/IntegrationsHubPage.tsx',
        'src/features/settings/roleAssignment.ts',
        'src/features/settings/RoleMultiSelect.tsx',
        'src/features/settings/networkAccess.ts',
        'src/features/settings/posSettingsAccess.ts',
        'src/features/settings/RolePermissionsMatrix.tsx',
        'src/hooks/useEntitlement.ts',
        'src/hooks/useFeatureFlag.ts',
        'src/hooks/useCurrentNetwork.ts',
        'src/components/auth/EnterpriseRouteGate.tsx',
        'src/components/auth/ModuleRouteGate.tsx',
        'src/components/auth/RequireModule.tsx',
        'src/components/layout/ProtectedRoute.tsx',
        'src/pages/UpgradePage.tsx',
        'src/pages/UnauthorizedPage.tsx',
        'src/lib/hrd.ts',
        'src/pages/showroom/ShowroomCheckoutPage.tsx',
      ],
      // CameraCapture / MediaPicker / TerminalPinPad: unit + Playwright e2e (not in threshold set).
      // Scanner PIN overlays: covered by Mobile-Scanner Playwright + store/hook unit tests.
      thresholds: {
        lines: 85,
        // Nested form helpers in SyncConflictsPanel are line-covered; function % sits just under 85.
        functions: 84,
        branches: 70,
        statements: 85,
      },
    },
  },
});
