import {
  AlertCircle,
  AlertTriangle,
  ArrowDownToLine,
  BarChart3,
  Barcode,
  Box,
  CircleHelp,
  ClipboardList,
  FilePlus,
  Link,
  ListTodo,
  Package,
  PackagePlus,
  Plus,
  Printer,
  Scale,
  Scan,
  Search,
  Shield,
  Undo2,
  Upload,
  Users,
  Waves,
  WifiOff,
  type LucideIcon,
} from 'lucide-react';

const PAGE_ACTION_ICONS: Record<string, LucideIcon> = {
  AlertCircle,
  AlertTriangle,
  ArrowDownToLine,
  BarChart: BarChart3,
  BarChart3,
  Barcode,
  Box,
  ClipboardList,
  FilePlus,
  Link,
  ListTodo,
  Package,
  PackagePlus,
  Plus,
  Printer,
  Scale,
  Scan,
  Search,
  Shield,
  Undo: Undo2,
  Undo2,
  Upload,
  Users,
  Waves,
  WifiOff,
};

/** Resolve a Lucide icon name from the page-knowledge dictionary. */
export function resolvePageActionIcon(name: string): LucideIcon {
  return PAGE_ACTION_ICONS[name] ?? CircleHelp;
}
