/**
 * Resolves optional chatbot/training module for the frontend.
 *
 * Usage:
 *   node scripts/resolve-chatbot.mjs              # auto (env + folder presence)
 *   node scripts/resolve-chatbot.mjs --enable     # force real module if present
 *   node scripts/resolve-chatbot.mjs --disable    # force stub
 *
 * Env: VITE_ENABLE_CHATBOT=false → stub (same as --disable)
 *
 * Page Info ("i") knowledge is NOT toggled here — it lives in src/lib/pageKnowledge.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const frontendRoot = path.resolve(__dirname, '..');
const moduleIndexTs = path.join(frontendRoot, 'src', 'modules', 'chatbot', 'index.ts');
const moduleIndexTsx = path.join(frontendRoot, 'src', 'modules', 'chatbot', 'index.tsx');
const activePath = path.join(frontendRoot, 'src', 'lib', 'chatbot', 'active.ts');
const flagPath = path.join(frontendRoot, '.chatbot-disabled');

const args = new Set(process.argv.slice(2));
const forceDisable =
  args.has('--disable') ||
  process.env.VITE_ENABLE_CHATBOT === 'false' ||
  fs.existsSync(flagPath);
const forceEnable = args.has('--enable');

if (forceEnable && fs.existsSync(flagPath)) {
  fs.unlinkSync(flagPath);
}

if (args.has('--disable')) {
  fs.writeFileSync(flagPath, 'Chatbot/training frontend module disabled.\n', 'utf8');
}

const modulePresent = fs.existsSync(moduleIndexTs) || fs.existsSync(moduleIndexTsx);
const moduleImport = '../../modules/chatbot';
const useModule = forceEnable
  ? modulePresent
  : !forceDisable && modulePresent;

if (forceEnable && !modulePresent) {
  console.warn(
    '[resolve-chatbot] --enable requested but src/modules/chatbot/index.(ts|tsx) is missing; using stub.',
  );
}

const header = `/**
 * AUTO-GENERATED by scripts/resolve-chatbot.mjs — do not edit by hand.
 * Mode: ${useModule ? 'MODULE (chatbot enabled)' : 'STUB (chatbot disabled / absent)'}
 * Generated: ${new Date().toISOString()}
 *
 * Page Info ("i") content is always in @/lib/pageKnowledge — not this bridge.
 */
`;

const body = useModule
  ? `export {
  ChatbotHost,
  recordSupportNetworkError,
  getTrainingGuard,
} from '${moduleImport}';
`
  : `export {
  ChatbotHost,
  recordSupportNetworkError,
  getTrainingGuard,
} from './stub';
`;

fs.writeFileSync(activePath, `${header}\n${body}`, 'utf8');
console.log(
  `[resolve-chatbot] active.ts → ${useModule ? 'src/modules/chatbot' : 'src/lib/chatbot/stub'}`,
);
