/**
 * Resolves optional chatbot + training frontend modules.
 *
 * Usage:
 *   node scripts/resolve-modules.mjs
 *   node scripts/resolve-modules.mjs --enable-chatbot|--disable-chatbot
 *   node scripts/resolve-modules.mjs --enable-training|--disable-training
 *
 * Env: VITE_ENABLE_CHATBOT=false / VITE_ENABLE_TRAINING=false
 * Markers: frontend/.chatbot-disabled , frontend/.training-disabled
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const frontendRoot = path.resolve(__dirname, '..');
const rawArgs = process.argv.slice(2).map((a) => {
  if (a === '--enable') return '--enable-chatbot';
  if (a === '--disable') return '--disable-chatbot';
  return a;
});
const args = new Set(rawArgs);

function resolveBridge({
  name,
  moduleDir,
  activeRel,
  stubImport,
  envKey,
  flagFile,
  enableArg,
  disableArg,
  exportNames,
}) {
  const moduleIndexTs = path.join(frontendRoot, 'src', 'modules', moduleDir, 'index.ts');
  const moduleIndexTsx = path.join(frontendRoot, 'src', 'modules', moduleDir, 'index.tsx');
  const activePath = path.join(frontendRoot, 'src', 'lib', ...activeRel.split('/'));
  const flagPath = path.join(frontendRoot, flagFile);

  const forceDisable =
    args.has(disableArg) ||
    process.env[envKey] === 'false' ||
    fs.existsSync(flagPath);
  const forceEnable = args.has(enableArg);

  if (forceEnable && fs.existsSync(flagPath)) {
    fs.unlinkSync(flagPath);
  }
  if (args.has(disableArg)) {
    fs.writeFileSync(flagPath, `${name} frontend module disabled.\n`, 'utf8');
  }

  const modulePresent = fs.existsSync(moduleIndexTs) || fs.existsSync(moduleIndexTsx);
  const useModule = forceEnable ? modulePresent : !forceDisable && modulePresent;
  if (forceEnable && !modulePresent) {
    console.warn(
      `[resolve-modules] ${enableArg} requested but src/modules/${moduleDir} missing; using stub.`,
    );
  }

  const header = `/**
 * AUTO-GENERATED by scripts/resolve-modules.mjs — do not edit by hand.
 * Mode: ${useModule ? `MODULE (${name} enabled)` : `STUB (${name} disabled / absent)`}
 * Generated: ${new Date().toISOString()}
 */
`;
  const names = exportNames.join(',\n  ');
  const body = useModule
    ? `export {\n  ${names}\n} from '../../modules/${moduleDir}';\n`
    : `export {\n  ${names}\n} from '${stubImport}';\n`;

  fs.mkdirSync(path.dirname(activePath), { recursive: true });
  fs.writeFileSync(activePath, `${header}\n${body}`, 'utf8');
  console.log(
    `[resolve-modules] ${name} → ${useModule ? `src/modules/${moduleDir}` : stubImport}`,
  );
}

resolveBridge({
  name: 'chatbot',
  moduleDir: 'chatbot',
  activeRel: 'chatbot/active.ts',
  stubImport: './stub',
  envKey: 'VITE_ENABLE_CHATBOT',
  flagFile: '.chatbot-disabled',
  enableArg: '--enable-chatbot',
  disableArg: '--disable-chatbot',
  exportNames: ['ChatbotHost', 'recordSupportNetworkError'],
});

resolveBridge({
  name: 'training',
  moduleDir: 'training',
  activeRel: 'training/active.ts',
  stubImport: './stub',
  envKey: 'VITE_ENABLE_TRAINING',
  flagFile: '.training-disabled',
  enableArg: '--enable-training',
  disableArg: '--disable-training',
  exportNames: ['TrainingHost', 'getTrainingGuard'],
});
