/**
 * AUTO-GENERATED by scripts/resolve-modules.mjs — do not edit by hand.
 * Mode: MODULE (training enabled)
 * Generated: 2026-07-22T23:32:32.834Z
 */

export {
  TrainingHost,
  getTrainingGuard
} from '../../modules/training';
