/**
 * AUTO-GENERATED by scripts/resolve-modules.mjs — do not edit by hand.
 * Mode: MODULE (training enabled)
 * Generated: 2026-07-23T19:55:22.302Z
 */

export {
  TrainingHost,
  getTrainingGuard
} from '../../modules/training';
