/**
 * AUTO-GENERATED by scripts/resolve-modules.mjs — do not edit by hand.
 * Mode: MODULE (training enabled)
 * Generated: 2026-07-22T20:29:41.689Z
 */

export {
  TrainingHost,
  getTrainingGuard
} from '../../modules/training';
