/**
 * AUTO-GENERATED by scripts/resolve-modules.mjs — do not edit by hand.
 * Mode: MODULE (training enabled)
 * Generated: 2026-08-17T16:35:37.523Z
 */

export {
  TrainingHost,
  getTrainingGuard
} from '../../modules/training';
