/**
 * AUTO-GENERATED by scripts/resolve-modules.mjs — do not edit by hand.
 * Mode: MODULE (training enabled)
 * Generated: 2026-08-24T13:28:51.903Z
 */

export {
  TrainingHost,
  getTrainingGuard
} from '../../modules/training';
