/**
 * AUTO-GENERATED by scripts/resolve-modules.mjs — do not edit by hand.
 * Mode: MODULE (training enabled)
 * Generated: 2026-08-22T03:26:41.735Z
 */

export {
  TrainingHost,
  getTrainingGuard
} from '../../modules/training';
