/**
 * AUTO-GENERATED by scripts/resolve-modules.mjs — do not edit by hand.
 * Mode: STUB (chatbot disabled / absent)
 * Generated: 2026-07-23T19:55:22.298Z
 */

export {
  ChatbotHost,
  recordSupportNetworkError
} from './stub';
