/**
 * AUTO-GENERATED by scripts/resolve-chatbot.mjs — do not edit by hand.
 * Mode: STUB (chatbot disabled / absent)
 * Generated: 2026-07-22T18:40:58.982Z
 *
 * Page Info ("i") content is always in @/lib/pageKnowledge — not this bridge.
 */

export {
  ChatbotHost,
  recordSupportNetworkError,
  getTrainingGuard,
} from './stub';
